name: Continous training
on:
  push:
    branches:
      - workflow_continous_training
  schedule:
    - cron: "0 */9 * * *"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the workflow"
        required: false
        default: "running CT"
jobs:
  continous-training:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 16
          uses: actions/setup-node@v1
          with:
            node-version: '16'
      - name: Ckeckout the repo
        uses: actions/checkout@v3
      - name: Train model
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-track
          dvc unprotect model/model.pkl
          dvc repro -f
          echo "Model trained"
          dvc add model/model.pkl
          dvc push model/model.pkl.dvc -r model-track
      - name: Commit .dvc file changes
        run: |
          git config --global user.email "valenciaestudillo@gmail.com"
          git config --global user.name "github-actions[bot]"
          git add model/model.pkl.dvc
          git commit -m "Update model/model.pkl.dvc serialization file"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: iterative/setup-cml@v1
      - name: Push metrics
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.txt >> report.md
          echo '![image](./prediction_behavior.png "Title")' >> report.md
          cml comment create report.md